services:
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile.debian
    image: treetips/frontend-nodejs:latest
    working_dir: /vscode/workspace
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/vscode/workspace:cached
      - ./docker/nodejs/.bashrc:/root/.bashrc
      # Volue Trick https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - node-modules:/vscode/workspace/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node-modules:
    driver: local
