version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    image: treetips/frontend-nodejs:latest
    working_dir: /vscode/workspace
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/vscode/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
