# LTS Code Name https://nodejs.org/ja/about/releases/
# Slim Docker Image https://hub.docker.com/r/oven/bun/tags?name=slim
FROM oven/bun:slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      curl git exa locales ca-certificates && \
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -y -f && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*
RUN sed -i -E 's/# (ja_JP.UTF-8)/\1/' /etc/locale.gen && \
    locale-gen
ENV LANG ja_JP.UTF-8

WORKDIR /vscode/workspace
